repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      # - id: no-commit-to-branch # prevent direct commits to the `main` branch
      - id: check-toml
      - id: check-yaml
        args: [ "--unsafe" ]
      - id: end-of-file-fixer
      - id: trailing-whitespace
